apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

patches:
  - path: replica-patch.yaml
    target:
      kind: Deployment

configMapGenerator:
  - name: platform-config
    behavior: merge
    literals:
      - SPRING_PROFILES_ACTIVE=dev

commonLabels:
  environment: dev
